CREATE TABLE TB_USER(
    USER_SEQ INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_USER_SEQ PRIMARY KEY (USER_SEQ)
) DEFAULT CHARSET=utf8;

CREATE TABLE TB_ROLE(
    ROLE_SEQ INT NOT NULL AUTO_INCREMENT,
    USER_SEQ INT NOT NULL,
    ROLE_ID VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_ROLE_SEQ PRIMARY KEY (ROLE_SEQ)
) DEFAULT CHARSET=utf8;

CREATE TABLE TB_OPERATION(
    OPERATION_SEQ INT NOT NULL AUTO_INCREMENT,
    ROLE_SEQ INT NOT NULL,
    OPERATION_ID VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_OPERATION_SEQ PRIMARY KEY (OPERATION_SEQ)
) DEFAULT CHARSET=utf8;


INSERT INTO TB_USER
  (USER_SEQ, USER_ID)
  VALUES
  (1, 'lms'),
  (2, 'rsa'),
  (3, 'lmj'),
  (4, 'sms');
  
INSERT INTO TB_ROLE
  (ROLE_SEQ, USER_SEQ, ROLE_ID)
  VALUES
  (1, 4, 'ROLE_D'),
  (2, 4, 'ROLE_C'),
  (3, 4, 'ROLE_B'),
  (4, 4, 'ROLE_A');

INSERT INTO TB_OPERATION
  (OPERATION_SEQ, ROLE_SEQ, OPERATION_ID)
  VALUES
  (1, 4, 'ROLE_SELECT'),
  (2, 4, 'ROLE_CREATE'),
  (3, 4, 'ROLE_UPDATE'),
  (4, 4, 'ROLE_DELETE');