CREATE TABLE TB_USER(
    USER_ID VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_ID PRIMARY KEY (USER_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE TB_ROLE(
    ROLE_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_ROLE_ID PRIMARY KEY (ROLE_ID, USER_ID)
) DEFAULT CHARSET=utf8;

CREATE TABLE TB_OPERATION(
    OPERATION_ID VARCHAR(100) NOT NULL,
    ROLE_ID VARCHAR(100) NOT NULL,
    
    CONSTRAINT PK_OPERATION_ID PRIMARY KEY (OPERATION_ID, ROLE_ID)
) DEFAULT CHARSET=utf8;


INSERT INTO TB_USER
  (USER_ID)
  VALUES
  ('lms'),
  ('rsa'),
  ('lmj'),
  ('sms');
  
INSERT INTO TB_ROLE
  (USER_ID, ROLE_ID)
  VALUES
  ('lms', 'ROLE_A'),
  ('rsa', 'ROLE_A'),
  ('lmj', 'ROLE_B'),
  ('sms', 'ROLE_A');

INSERT INTO TB_OPERATION
  (OPERATION_ID, ROLE_ID)
  VALUES
  ('ROLE_SELECT', 'ROLE_A'),
  ('ROLE_CREATE', 'ROLE_A'),
  ('ROLE_UPDATE', 'ROLE_A'),
  ('ROLE_DELETE', 'ROLE_A');